import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Portafolio - Seba Monsalve</title>
      </head>
      <body  >

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="transition-all dark:bg-[#243141] dark:text-slate-300 ">

            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
